baseURL = "https://luisjosetorres12.github.io/luisjosetorres.github.io/"
languageCode = "es-co"
title = "Cibersecurity Notes by Luisjo"
theme = "PaperMod"
publishDir = "docs"

[params]
  author = "Luis Torres"
  description = "Notas de Ciberseguridad, una guia de mi camino para ir aprendiendo y documentando cosas"